name: Testing customized issue template
description: Customized issue template
title: "[Customized issue tempalte] "
labels: ["Ansita's branch"]
projects: ["Ansita's Customized testing project"]
assignees:
  - Ansita
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue template report!
  - type: input
    id: name
    attributes:
      label: ACR name
      description: Enter ACR name
    validations:
      required: true
  - type: input
    id: pass
    attributes:
      label: ACR pass-word
      description: Enter ACR password
    validations:
      required: true
  - type: input
    id: username
    attributes:
      label: ACR username
      description: Enter ACR username
    validations:
      required: true
  
