name: Store Issue Secrets

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Issue Details
        id: get_issue
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"

      - name: Extract Password
        id: extract_password
        run: |
          # Extract the password using a regex pattern or simple string matching
          password=$(echo "${{ github.event.issue.body }}" | grep -oP 'Password:\s*\K.*')
          echo "Password Extracted: $password"
          echo "::set-output name=password::$password"

      - name: Store Password in GitHub Secrets
        run: |
          # Using GitHub's REST API to create or update a secret
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"encrypted_value\":\"$(echo -n "${{ steps.extract_password.outputs.password }}" | base64)\", \"visibility\":\"all\"}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/secrets/PASSWORD_SECRET"

      - name: Update Issue to Mask Password
        run: |
          # Replace the password in the issue body with a placeholder
          updated_body=$(echo "${{ github.event.issue.body }}" | sed 's/Password:.*$/Password: [REDACTED]/')
          
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"body\":\"$updated_body\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
